"
Visitor implementa el patrón Visitor.
"
Class {
	#name : #Visitor,
	#superclass : #Object,
	#category : #'JuegoLaberinto-Visitor'
}

{ #category : #'as yet unclassified' }
Visitor >> visitarArmario:unaArmario [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarBomba:unaBomba [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarHabitacion:unaHab [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPared:unaPared [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPuerta:unaPuerta [
]

{ #category : #'as yet unclassified' }
Visitor >> visitarTunel:unaTunel [
]
